[theme]
base="light"
primaryColor = "#6D4C41"                
backgroundColor = "#FFFFFF"              
secondaryBackgroundColor = "#F5F5F5"     
textColor = "#3E2723"                    
font = "sans serif"  

[server]
headless = true                       
runOnSave = true                  
